### ISSUE TITLE
您好，请问ontonote4的处理方式与ontonote5相同么，感谢

### ISSUE THREAD

**Issue by tyistyler** [HuHsinpang/Ontonotes5.0-pretreatment#1]

**Comment by HuHsinpang** [comment]
这个我不知道诶，因为我们学校没有那个网站数据的权限，所以找同学下载了ontonote5.0的数据，没有4.0版本的，自己只做了5.0的处理程序，两个处理方式有什么区别不清楚。不过我记得官网上有介绍，说是5.0在4.0的基础上做的，数据来源更广泛，实体类别更多，数据量更大，我觉得用5.0更好，你可以看看

**Comment by tyistyler** [comment]
好的，谢谢
