### ISSUE TITLE
处理程序的链接不能用

### ISSUE THREAD

**Issue by syuoni** [HuHsinpang/Ontonotes5.0-pretreatment#2]
处理程序的链接好像不能用了，能不能请发一份给我（邮箱：spiritas@163.com）？谢谢。

**Comment by guopeiming** [comment]
处理程序的链接不能用啦， @HuHsinpang 可以将处理程序push到本项目里面吗？

**Comment by HuHsinpang** [comment]
诶呦，这个还真没发现，一会我传一下

**Comment by guopeiming** [comment]
哈哈哈，谢谢啦，不过我好像找到新的下载链接了。应该是这个吧？[http://conll.cemantix.org/2012/download/](http://conll.cemantix.org/2012/download/)。是的话，在readme里面也更新一下链接吧~ @HuHsinpang @syuoni

**Comment by HuHsinpang** [comment]
> 哈哈哈，谢谢啦，不过我好像找到新的下载链接了。应该是这个吧？http://conll.cemantix.org/2012/download/。是的话，在readme里面也更新一下链接吧~ @HuHsinpang @syuoni

对，是这个链接，记得对着图片下载哈，我把链接更新一下

**Comment by guopeiming** [comment]
> > 哈哈哈，谢谢啦，不过我好像找到新的下载链接了。应该是这个吧？[http://conll.cemantix.org/2012/download/。是的话，在readme里面也更新一下链接吧](http://conll.cemantix.org/2012/download/%E3%80%82%E6%98%AF%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%9C%A8readme%E9%87%8C%E9%9D%A2%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E9%93%BE%E6%8E%A5%E5%90%A7)~ @HuHsinpang @syuoni
> 
> 对，是这个链接，记得对着图片下载哈，我把链接更新一下

不过我有几个问题想问一下：
1. 你的这个最后处理的结果，主要是train/dev/test的划分结果和yhcc同学那个结果是一样的嘛。因为后面可能涉及到结果对比，得先保证数据集是一样的。
2. 解压出来的文件里面，我看有v4，有v3，有v9，最后的数据集划分，是用的v4版本的嘛？

**Comment by HuHsinpang** [comment]
> > > 哈哈哈，谢谢啦，不过我好像找到新的下载链接了。应该是这个吧？[http://conll.cemantix.org/2012/download/。是的话，在readme里面也更新一下链接吧](http://conll.cemantix.org/2012/download/%E3%80%82%E6%98%AF%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%9C%A8readme%E9%87%8C%E9%9D%A2%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E9%93%BE%E6%8E%A5%E5%90%A7)~ @HuHsinpang @syuoni
> > 
> > 
> > 对，是这个链接，记得对着图片下载哈，我把链接更新一下
> 
> 不过我有几个问题想问一下：
> 
> 1. 你的这个最后处理的结果，主要是train/dev/test的划分结果和yhcc同学那个结果是一样的嘛。因为后面可能涉及到结果对比，得先保证数据集是一样的。
> 2. 解压出来的文件里面，我看有v4，有v3，有v9，最后的数据集划分，是用的v4版本的嘛？

切分这块是那个网站上的处理程序切分的，是官方给的，是v4版本，我就只是把后续的工作做了一下

**Comment by HuHsinpang** [comment]
> 处理程序的链接好像不能用了，能不能请发一份给我（邮箱：[spiritas@163.com](mailto:spiritas@163.com)）？谢谢。

那个处理程序还挺大的。readme更新了一下，你试试看能不能解决你的问题。

**Comment by syuoni** [comment]
谢谢。那个下载的链接后来我也发现了。看来只是页面挂了。

**Comment by syuoni** [comment]
> > > 哈哈哈，谢谢啦，不过我好像找到新的下载链接了。应该是这个吧？[http://conll.cemantix.org/2012/download/。是的话，在readme里面也更新一下链接吧](http://conll.cemantix.org/2012/download/%E3%80%82%E6%98%AF%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%9C%A8readme%E9%87%8C%E9%9D%A2%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E9%93%BE%E6%8E%A5%E5%90%A7)~ @HuHsinpang @syuoni
> > 
> > 
> > 对，是这个链接，记得对着图片下载哈，我把链接更新一下
> 
> 不过我有几个问题想问一下：
> 
> 1. 你的这个最后处理的结果，主要是train/dev/test的划分结果和yhcc同学那个结果是一样的嘛。因为后面可能涉及到结果对比，得先保证数据集是一样的。
> 2. 解压出来的文件里面，我看有v4，有v3，有v9，最后的数据集划分，是用的v4版本的嘛？

我的处理结果是这样的，和论文里 OntoNotes5 的结果一致：

英文的
|        | #Sent | #Ent | #Token |
|:-----:|:----:|:-------:|:------:|
| Train | 59,924 | 81,828 | 1,088,503 |
| Dev  |   8,528 | 11,066 |   147,724 |
| Test  |   8,262 | 11,257 |   152,728 | 

中文的
|        | #Sent | #Ent | #Token |
|:-----:|:----:|:-------:|:------:|
| Train | 36,487 | 62,543 | 756,063 |
| Dev  |   6,083 | 9,104 |   110,034 |
| Test  |    4,472 | 7,494 |   92,308 |

**Comment by guopeiming** [comment]
> 我的处理结果是这样的，和论文里 OntoNotes5 的结果一致：
> 
> 英文的
> 
> #Sent	#Ent	#Token
> Train	59,924	81,828	1,088,503
> Dev	8,528	11,066	147,724
> Test	8,262	11,257	152,728
> 中文的
> 
> #Sent	#Ent	#Token
> Train	36,487	62,543	756,063
> Dev	6,083	9,104	110,034
> Test	4,472	7,494	92,308

不好意思，现在才看到，我中文的结果跟您一样，英文不太一样。我想问一下，您说的“论文里的OntoNotes5”参考的是哪一篇论文呀？方便说一下嘛

**Comment by syuoni** [comment]
> > 我的处理结果是这样的，和论文里 OntoNotes5 的结果一致：
> > 英文的
> > #Sent	#Ent	#Token
> > Train	59,924	81,828	1,088,503
> > Dev	8,528	11,066	147,724
> > Test	8,262	11,257	152,728
> > 中文的
> > #Sent	#Ent	#Token
> > Train	36,487	62,543	756,063
> > Dev	6,083	9,104	110,034
> > Test	4,472	7,494	92,308
> 
> 不好意思，现在才看到，我中文的结果跟您一样，英文不太一样。我想问一下，您说的“论文里的OntoNotes5”参考的是哪一篇论文呀？方便说一下嘛

Chiu and Nichols. 2016. Named entity recognition with bidirectional LSTM-CNNs.

**Comment by syuoni** [comment]
> > 我的处理结果是这样的，和论文里 OntoNotes5 的结果一致：
> > 英文的
> > #Sent	#Ent	#Token
> > Train	59,924	81,828	1,088,503
> > Dev	8,528	11,066	147,724
> > Test	8,262	11,257	152,728
> > 中文的
> > #Sent	#Ent	#Token
> > Train	36,487	62,543	756,063
> > Dev	6,083	9,104	110,034
> > Test	4,472	7,494	92,308
> 
> 不好意思，现在才看到，我中文的结果跟您一样，英文不太一样。我想问一下，您说的“论文里的OntoNotes5”参考的是哪一篇论文呀？方便说一下嘛

看这个链接：https://github.com/allanj/pytorch_lstmcrf/blob/master/docs/benchmark.md

**Comment by zhanghaok** [comment]
> 诶呦，这个还真没发现，一会我传一下

博主大大，你好。能不能分享一下处理好的OneNotes5.0 BIO标注的数据集呀，我这边装py2.7的环境装不上呜呜呜，我的邮箱3250514239@qq.com
